export ADQM_OUT='/net/scratch_cms3a/daumann/qualification_task_muons/AutoDQM/runoffline/out'
export ADQM_PLUGINS='/net/scratch_cms3a/daumann/qualification_task_muons/AutoDQM/plugins'
export ADQM_CONFIG='/net/scratch_cms3a/daumann/qualification_task_muons/AutoDQM/config'
export ADQM_DB='/net/scratch_cms3a/daumann/qualification_task_muons/AutoDQM/runoffline/db'
export ADQM_TMP='/net/scratch_cms3a/daumann/qualification_task_muons/AutoDQM/runoffline/tmp'
export ADQM_SSLCERT='/home/home1/institut_3a/daumann/.globus/usercert.pem'
export ADQM_SSLKEY='/home/home1/institut_3a/daumann/.globus/userkey.pem'
export ADQM_CACERT='/home/home1/institut_3a/daumann/.globus/myCert.p12'
